### ISSUE TITLE
Umineko patch mod options with little or no documentation

### ISSUE THREAD

**Issue by kihyvari** [07th-mod/wiki#16]
During installing the patch for Umineko I had to check the discord channel what these mod options exactly meant.

![kuva](https://user-images.githubusercontent.com/60000042/80909373-74751c00-8d30-11ea-8ff4-f945d1b2bd77.png)

I suggest updating the [User Wiki](https://07th-mod.com/wiki/Umineko/Umineko-Mod-Options/) with some type of explanations about these options. User Lk had this useful description in #umi_support channel:

> system0 has a sample from Star Trek: Nemesis in it that the console version removed. The mod puts it back.
> 
> In Turn of the Golden Witch, there is a bit where Jessica sings a song. Originally, it was Tsurupettan, which is a Touhou song, and included a CG that referenced Touhou. The console version replaced the song with an original song and a different CG.
> 
> Both of these were apparently done for copyright reasons.

**Comment by drojf** [comment]
good point. We should update the information in the installer itself too.

I might modify the text to avoid specifics, as people might consider some information spoiler.

**Comment by drojf** [comment]
this should be fixed now, both on the wiki and the installer. thanks for reporting this kihyvari
