### ISSUE TITLE
Wiki Improvements List

### ISSUE THREAD

**Issue by drojf** [07th-mod/wiki#18]
## Higurashi Wiki

- [x] Add comparison screenshots between our mod and the base game (currently there are no screenshots at all!) so you can quickly see what the mod visually adds
- [x] Add a comparison between the sprite types, (and backgrounds when that is completed), the same as is done in the umineko [wiki](https://07th-mod.com/wiki/Umineko/Umineko-Mod-Options/)
- [x] Move information about patch features from the "Installer" page to the "Intro" page
- [x] State that one of the Higurashi mod features is converting to widescreen from 4:3 resolution. We also state the ps3 sprites and mangagamer sprites are 1440p, the backgrounds are 1080p, but we don't explicitly state the game resolution has been patched to widescreen 1080p (or why having 1440p sprites are a benefit in 1080p...does Higurashi actually render higher than 1440p if you have a high res monitor?).
- [x] Have a little paragraph giving some background on the console arcs - currently there are bits and pieces of information (which is good), but no overall "what is the console arcs"
- [ ] **Unsure**: Make a new page for the console arcs? Currently it occupies a heap of space on the "Intro" page with the flowchart, when that page should be more for a user to see what we offer, and what patch patch options. But at the same time I don't want people to miss the console arcs. Not sure best way to handle this.

**Comment by ItaloKnox** [comment]
I can handle this, I already have a general idea on how to make it better.
Just need a few days since my CPU cooler is apparently dead and a new one
in on it's way.

Em ter, 6 de out de 2020 11:35, D.W <notifications@github.com> escreveu:
