### ISSUE TITLE
"Reporting Issues" page needs update

### ISSUE THREAD

**Issue by drojf** [07th-mod/wiki#2]
This page: http://07th-mod.com/wiki/Support/

- Generally the page needs to be updated for the new wiki

- The page should probably be renamed "Getting Help / Support / Reporting Bugs" so that it's more of a general "HELP ME" page

- It should link to the discord server and maybe have an individual link to each repository, as the end user wouldn't know how to navigate to each repository.

- End users might not know how to report Issues. Git already provides a nice guide on how to report an issues here:
    - Tell them to create an account here: https://github.com/join 
    - Tell them to create an issue following instructions here: https://help.github.com/en/articles/creating-an-issue

- Also tell the user to follow the template (and add it is a **suggestion**. If we tell them to always follow the template, they may give up if the template is too long):

- if the majority of issues we get are reported via discord, a simple discord bot would be nice, although I've never set one up before

----

Here's the current umineko report template:

```
Here is a template you can use for reporting bugs. It is just a suggestion - some items might not be relevant to your issue.

- [a description of the issue]
- [pictures of the issue (if applicable)]
- The bug occurs just after [text from when bug occurs] is shown on the screen
- My operating system is [Windows, MacOS, Linux]
- I installed the game [X Months ago]
- I am running the [Full Patch / Voice only patch]
- I installed the game [Manually / using the Automatic Installer]
- My computer is a [Gaming Beast / Laptop with Integrated Graphics]
- Add the stderr.txt and stdout.txt to the post, as described above.

For issues where the game crashes or behaves badly, it is extremely useful to get the game's error log. Newer auto-installations can simply double click the "Umineko1to4_DebugMode.bat" file to start the game in debug mode.

Once you have started the game in debug mode, just play until the game crashes or behaves badly, then submit the stderr.txt and stdout.txt to us (when game is started in debug mode, a folder will appear showing stderr.txt and stdout.txt).

If you're not sure if it's a bug, you can report it on our discord (but try not to post any spoilers, if possible).
We really appreciate your help!
```

**Comment by ItaloKnox** [comment]
Yeah, that's pretty much a neglected page that needs some updates. I'll look into it today or early tomorrow and adapt your template to also fit Higurashi accordingly.

I was also thinking about a Discord bot since last week, I tried looking for something but it was hard to find Github bots for Discord, usually, Google only returns Discord bots on Github. It would be cool if we had a bot that could list current open issues on certain repositories or search for issues in general. I'm not so sure about opening issues from Discord, that might be clunky and prone to abuse.
