### ISSUE TITLE
Manual Downloads page: "Please see this FAQ to understand what the BGM/SE Fixes do" message is in the wrong place

### ISSUE THREAD

**Issue by webbedspace** [07th-mod/wiki#28]
![image](https://user-images.githubusercontent.com/83939/148246986-34814ddf-f8c3-4a69-bf77-0ef2b600bc78.png)

The message highlighted in red is in the Optional Q/A Downloads tab, even though the fixes it refers to are in the Question Arcs and Answer Arcs tab instead.

**Comment by ItaloKnox** [comment]
Thanks for noticing that, it was like that a long time ago, but since then we changed the fixes from optional to required. Somehow we forgot to move the message to its proper place, but it's now fixed. Once again, thanks!
