### ISSUE TITLE
Manual Instructions for Console Arcs on MacOS

### ISSUE THREAD

**Issue by FatesTimelines1337** [07th-mod/wiki#45]
The current instructions for manual installation for MacOS state for all Higurashi archives without an emoji marker should be extracted to the `Resources/Data` folder. However, the system files instead need to be extracted to where the `Contents` folder is located, which the installer correctly does. The manual instructions do not say that therefore they would end up inside the `Resources/Data` folder.

**Comment by ItaloKnox** [comment]
PR #46 looks good, I'll merge it. Thanks!
