### ISSUE TITLE
Voice matching level description is out of date

### ISSUE THREAD

**Issue by drojf** [07th-mod/wiki#8]
Currently it says the voice matching level goes from 0-3, but it goes from 0-5

http://07th-mod.com/wiki/Higurashi/Higurashi-Part-2---Patch-configuration-and-keyboard-shortcuts/

May want to add a short paragraph description of what the option does as it's not immediately obvious if you don't have any background on how the voices were ported from the ps3 game.

**Comment by drojf** [comment]
The up-to-date information is here: https://github.com/07th-mod/higurashi-patch-compiler/wiki/Notes

**Comment by ItaloKnox** [comment]
I thought I already updated that but looks like I didn't. I'm inclined to remove the page since the shortcuts are already better listed in-game. Should we do it, @enumag?

**Comment by enumag** [comment]
@ItaloKnox Yeah, I agree with removal.

**Comment by ItaloKnox** [comment]
I'll unlist it, the page will still work if you have the link but it won't be shown anywhere in the wiki. This way we will have a fallback in case we need it.

**Comment by enumag** [comment]
You can just remove it. It will always stay in the git history in case we ever need it so it's easy to revert it any time.

**Comment by ItaloKnox** [comment]
Wiki update is already up. This can be closed now.
